// <auto-generated />
using System;
using CatalogNavigator.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatalogNavigator.DataLayer.Migrations
{
    [DbContext(typeof(CatalogDB))]
    partial class CatalogDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatalogNavigator.DataLayer.Model.Catalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Catalogs");
                });

            modelBuilder.Entity("CatalogNavigator.DataLayer.Model.Catalog", b =>
                {
                    b.HasOne("CatalogNavigator.DataLayer.Model.Catalog", null)
                        .WithMany("SubCatalogs")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("CatalogNavigator.DataLayer.Model.Catalog", b =>
                {
                    b.Navigation("SubCatalogs");
                });
#pragma warning restore 612, 618
        }
    }
}
